language: node_js
sudo: required
dist: trusty
node_js: '10'
addons:
  chrome: stable
cache:
  directories:
  - node_modules
matrix:
  fast_finish: true

  include:
    - env: JOB=test
      before_script:
        - npm run bundle
      script:
        - wtc -s 'Linux/chrome@62' --npm
